<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SchoolCollab.Admin\SchoolCollab.Admin.csproj" />
    <ProjectReference Include="..\..\src\SchoolCollab.Core\SchoolCollab.Core.csproj" />
    <ProjectReference Include="..\..\src\Students\SchoolCollab.Students.Application\SchoolCollab.Students.Application.csproj" />
  </ItemGroup>

</Project>