<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0436</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SchoolCollab.CodedValues.Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ServiceDefaults\SchoolCollab.ServiceDefaults\SchoolCollab.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SchoolCollab.CodedValues.Contracts\SchoolCollab.CodedValues.Contracts.csproj" />
    <ProjectReference Include="..\SchoolCollab.CodedValues.AI\SchoolCollab.CodedValues.AI.csproj" />
  </ItemGroup>
</Project>
