<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0436</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SchoolCollab.Students.Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SchoolCollab.Admin.Shared\SchoolCollab.Admin.Shared.csproj" />
    <ProjectReference Include="..\SchoolCollab.Students.Contracts\SchoolCollab.Students.Contracts.csproj" />
    <ProjectReference Include="..\SchoolCollab.Students.Core\SchoolCollab.Students.Core.csproj" />
  </ItemGroup>
</Project>