using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using SchoolCollab.Assignments.Api.Services;
using SchoolCollab.Assignments.Core.Domain;
using SchoolCollab.Assignments.Core.Services;

namespace SchoolCollab.Assignments.Api.Tests.Unit;

/// <summary>
/// C3 — the QuestPDF certificate renderer (decision (a), amendment A-1: the
/// generator lives in the Assignments.Api layer — the only runtime that
/// dispatches finalize — so these tests live in the Api test project, which is
/// the one that references the Api assembly). Asserts the exported PDF shape,
/// that both signature types render, and that long / multi-paragraph consent
/// text does not blow up the layout.
/// </summary>
[TestClass]
public class AssignmentCertificateGeneratorTests
{
    private static readonly Guid StudentId = Guid.Parse("00000000-0000-0000-0000-000000000ab1");
    private static readonly Guid GuardianId = Guid.Parse("00000000-0000-0000-0000-000000000ab2");

    private static AssignmentCertificateGenerator Generator =>
        new(NullLogger<AssignmentCertificateGenerator>.Instance);

    private static AssignmentCertificateContent Content(
        SignatureType signatureType = SignatureType.Click,
        string? typedSignature = null,
        string consentText = "By signing I consent to the publication of this assignment outcome.")
    {
        var signed = new DateTimeOffset(new DateTime(2026, 3, 2, 9, 30, 0, DateTimeKind.Utc));
        var finalized = signed.AddHours(2);
        return new AssignmentCertificateContent(
            "Math HW",
            "Ward One",
            "Jane Doe",
            signatureType,
            typedSignature,
            signed,
            finalized,
            consentText);
    }

    [TestMethod]
    public async Task Generates_NonEmptyPdf_WithPdfHeader()
    {
        var bytes = await Generator.GenerateAsync(Content(), CancellationToken.None);

        bytes.Should().NotBeNullOrEmpty();
        bytes.Should().HaveCountGreaterThan(500, "a one-page A4 certificate is a non-trivial PDF");
        bytes.Length.Should().BeGreaterThan(500);
        bytes.AsSpan(0, 4).SequenceEqual("%PDF"u8).Should().BeTrue("the generated bytes carry the PDF header");
    }

    [TestMethod]
    public async Task Renders_BothSignatureTypes()
    {
        var typed = await Generator.GenerateAsync(
            Content(SignatureType.Typed, "Jane Doe"), CancellationToken.None);
        var click = await Generator.GenerateAsync(
            Content(SignatureType.Click, null), CancellationToken.None);

        typed.Should().NotBeNullOrEmpty();
        click.Should().NotBeNullOrEmpty();
        typed.AsSpan(0, 4).SequenceEqual("%PDF"u8).Should().BeTrue();
        click.AsSpan(0, 4).SequenceEqual("%PDF"u8).Should().BeTrue();
    }

    [TestMethod]
    public async Task LongConsentText_DoesNotThrow()
    {
        var multiParagraph = string.Join("\n\n",
            Enumerable.Range(1, 6).Select(i =>
                $"Consent paragraph {i}: the guardian has reviewed the assignment instructions, " +
                "the marking rubric and the publication terms before signing."));

        // Awaiting directly is the assertion: a layout error throws and fails the test.
        var bytes = await Generator.GenerateAsync(Content(consentText: multiParagraph), CancellationToken.None);

        bytes.Should().NotBeNullOrEmpty();
        bytes.AsSpan(0, 4).SequenceEqual("%PDF"u8).Should().BeTrue();
    }
}
