<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.5" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>71bc1e6c-899e-4131-98f2-60199f7d3ba2</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Settings\SchoolCollab.Settings.Contracts\SchoolCollab.Settings.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Settings\SchoolCollab.Settings.Core\SchoolCollab.Settings.Core.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Settings\SchoolCollab.Settings.Api\SchoolCollab.Settings.Api.csproj" />
    <ProjectReference Include="..\..\SchoolCollab.Admin\SchoolCollab.Admin.csproj" />
    <ProjectReference Include="..\..\SchoolCollab.AI.Server\SchoolCollab.AI.Server.csproj" />
    <ProjectReference Include="..\..\SchoolCollab.MigrationService\SchoolCollab.MigrationService.csproj" />
    <ProjectReference Include="..\..\Assignments\SchoolCollab.Assignments.Contracts\SchoolCollab.Assignments.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Assignments\SchoolCollab.Assignments.Core\SchoolCollab.Assignments.Core.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Assignments\SchoolCollab.Assignments.Api\SchoolCollab.Assignments.Api.csproj" />
    <ProjectReference Include="..\..\Students\SchoolCollab.Students.Contracts\SchoolCollab.Students.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Students\SchoolCollab.Students.Core\SchoolCollab.Students.Core.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Students\SchoolCollab.Students.Api\SchoolCollab.Students.Api.csproj" />
    <ProjectReference Include="..\..\Students\SchoolCollab.Students.Worker\SchoolCollab.Students.Worker.csproj" />
  </ItemGroup>
</Project>
