// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolCollab.Students.Core.Data;

#nullable disable

namespace SchoolCollab.Students.Core.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20260830060725_AddPeriodDivision")]
    partial class AddPeriodDivision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolCollab.Core.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("ix_outbox_messages_dispatched_at");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenewDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew_default");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EnrollmentEndDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_end_date");

                    b.Property<DateOnly?>("EnrollmentStartDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_start_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextEnrollmentEndDate")
                        .HasColumnType("date")
                        .HasColumnName("next_enrollment_end_date");

                    b.Property<DateOnly?>("NextEnrollmentStartDate")
                        .HasColumnType("date")
                        .HasColumnName("next_enrollment_start_date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Span")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("span");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity_groups");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_activity_groups_tenant_active");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_activity_groups_tenant_name");

                    b.ToTable("activity_groups", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupGradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_group_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity_group_grade_levels");

                    b.HasIndex("ActivityGroupId")
                        .HasDatabaseName("ix_activity_group_grade_levels_activity_group_id");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_activity_group_grade_levels_grade_level_id");

                    b.HasIndex("TenantId", "GradeLevelId")
                        .HasDatabaseName("ix_agg_tenant_grade");

                    b.HasIndex("TenantId", "ActivityGroupId", "GradeLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_agg_tenant_group_grade_unique");

                    b.ToTable("activity_group_grade_levels", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_group_id");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExitedOn")
                        .HasColumnType("date")
                        .HasColumnName("exited_on");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("WindowEndDate")
                        .HasColumnType("date")
                        .HasColumnName("window_end_date");

                    b.Property<DateOnly?>("WindowStartDate")
                        .HasColumnType("date")
                        .HasColumnName("window_start_date");

                    b.HasKey("Id")
                        .HasName("pk_activity_group_memberships");

                    b.HasIndex("ActivityGroupId")
                        .HasDatabaseName("ix_activity_group_memberships_activity_group_id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_activity_group_memberships_period_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_activity_group_memberships_student_id");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("ix_agm_tenant_student");

                    b.HasIndex("TenantId", "ActivityGroupId", "Status")
                        .HasDatabaseName("ix_agm_tenant_group_status");

                    b.HasIndex("TenantId", "StudentId", "ActivityGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_agm_tenant_student_group_active")
                        .HasFilter("status = 0 AND period_id IS NULL");

                    b.HasIndex("TenantId", "StudentId", "ActivityGroupId", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("ix_agm_tenant_student_group_period_active")
                        .HasFilter("status = 0 AND period_id IS NOT NULL");

                    b.ToTable("activity_group_memberships", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("TenantId", "OwnerType", "OwnerId")
                        .HasDatabaseName("ix_contacts_tenant_owner");

                    b.HasIndex("TenantId", "OwnerType", "OwnerId", "Channel", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_tenant_owner_channel_value");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ContactAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("change_kind");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("NewChannel")
                        .HasColumnType("integer")
                        .HasColumnName("new_channel");

                    b.Property<string>("NewCountryCode")
                        .HasColumnType("text")
                        .HasColumnName("new_country_code");

                    b.Property<string>("NewLabel")
                        .HasColumnType("text")
                        .HasColumnName("new_label");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<int>("PreviousChannel")
                        .HasColumnType("integer")
                        .HasColumnName("previous_channel");

                    b.Property<string>("PreviousCountryCode")
                        .HasColumnType("text")
                        .HasColumnName("previous_country_code");

                    b.Property<string>("PreviousLabel")
                        .HasColumnType("text")
                        .HasColumnName("previous_label");

                    b.Property<string>("PreviousValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_value");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contact_audit_entries");

                    b.HasIndex("TenantId", "ContactId")
                        .HasDatabaseName("ix_contact_audit_entries_tenant_contact");

                    b.HasIndex("TenantId", "OwnerType", "OwnerId", "OccurredAt")
                        .HasDatabaseName("ix_contact_audit_entries_tenant_owner_occurred");

                    b.ToTable("contact_audit_entries", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ContactSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<Guid?>("ScopeRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_ref_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contact_subscriptions");

                    b.HasIndex("TenantId", "ContactId", "Scope", "ScopeRefId")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_subscriptions_tenant_contact_scope");

                    b.ToTable("contact_subscriptions", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AllowedGenderCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("allowed_gender_coded_value_id");

                    b.Property<Guid>("CodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("coded_value_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsBlockedFromEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked_from_enrollment");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("max_age");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grade_levels");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_grade_levels_level");

                    b.HasIndex("TenantId", "CodedValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_levels_tenant_coded_value_id");

                    b.ToTable("grade_levels", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GradeNotificationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockedChannels")
                        .HasColumnType("jsonb")
                        .HasColumnName("blocked_channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("LinkValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("link_validity_days");

                    b.Property<int?>("MaxNotifications")
                        .HasColumnType("integer")
                        .HasColumnName("max_notifications");

                    b.Property<int?>("MaxReminders")
                        .HasColumnType("integer")
                        .HasColumnName("max_reminders");

                    b.Property<string>("PreferredChannelOrder")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_channel_order");

                    b.Property<int?>("ReminderIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_interval_hours");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("SendoutIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sendout_interval_minutes");

                    b.Property<TimeOnly?>("SendoutTimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("sendout_time_of_day");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grade_notification_policies");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_grade_notification_policies_grade_level_id");

                    b.HasIndex("TenantId", "GradeLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_notification_policies_tenant_grade")
                        .HasFilter("is_deleted = false");

                    b.ToTable("grade_notification_policies", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("GenderCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("gender_coded_value_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TitleCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_coded_value_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guardians");

                    b.HasIndex("TenantId", "LastName")
                        .HasDatabaseName("ix_guardians_tenant_last_name");

                    b.ToTable("guardians", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GuardianNameHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guardian_name_history");

                    b.HasIndex("TenantId", "GuardianId")
                        .HasDatabaseName("ix_guardian_name_history_tenant_guardian");

                    b.ToTable("guardian_name_history", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.LocalCodedValue", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("row_id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_code");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RowId")
                        .HasName("pk_local_coded_values");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_local_coded_values_code");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_local_coded_values_tenant_id");

                    b.ToTable("local_coded_values", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Division")
                        .HasColumnType("integer")
                        .HasColumnName("division");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("NextPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_period_id");

                    b.Property<Guid?>("ParentPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_period_id");

                    b.Property<int>("PeriodType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("period_type");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("ParentPeriodId")
                        .HasDatabaseName("ix_periods_parent_period_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_periods_start_date");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_one_active_year")
                        .HasFilter("period_type = 0 AND status = 1");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_periods_tenant_status");

                    b.HasIndex("TenantId", "ParentPeriodId", "PeriodType")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_one_active_sub_period")
                        .HasFilter("status = 1");

                    b.HasIndex("TenantId", "ParentPeriodId", "Status")
                        .HasDatabaseName("ix_periods_tenant_parent_status");

                    b.HasIndex("TenantId", "PeriodType", "Status")
                        .HasDatabaseName("ix_periods_tenant_type_status");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("GenderCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("gender_coded_value_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TitleCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_coded_value_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("GenderCodedValueId")
                        .HasDatabaseName("ix_students_gender_cv_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_students_is_deleted");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("ix_students_tenant_id_is_deleted");

                    b.HasIndex("TenantId", "StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_students_tenant_student_number");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EnrolledOn")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_on");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("date")
                        .HasColumnName("exit_date");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("StreamCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_coded_value_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransferReason")
                        .HasColumnType("text")
                        .HasColumnName("transfer_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WithdrawReason")
                        .HasColumnType("text")
                        .HasColumnName("withdraw_reason");

                    b.HasKey("Id")
                        .HasName("pk_student_enrollments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_student_enrollments_status");

                    b.HasIndex("TenantId", "GradeLevelId")
                        .HasDatabaseName("ix_student_enrollments_tenant_grade_level");

                    b.HasIndex("TenantId", "PeriodId")
                        .HasDatabaseName("ix_student_enrollments_tenant_period");

                    b.HasIndex("TenantId", "StreamCodedValueId")
                        .HasDatabaseName("ix_student_enrollments_tenant_stream");

                    b.HasIndex("TenantId", "StudentId", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_enrollments_tenant_student_period");

                    b.ToTable("student_enrollments", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.StudentGuardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_guardian_id");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_id");

                    b.Property<bool>("IsEmergencyContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_emergency_contact");

                    b.Property<Guid?>("RelationshipCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_coded_value_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student_guardians");

                    b.HasIndex("TenantId", "GuardianId")
                        .HasDatabaseName("ix_student_guardians_tenant_guardian");

                    b.HasIndex("TenantId", "StudentId", "GuardianId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_guardians_tenant_student_guardian");

                    b.ToTable("student_guardians", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.StudentTopicAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_override");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source_type");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student_topic_assignments");

                    b.HasIndex("TenantId", "PeriodId")
                        .HasDatabaseName("ix_student_topic_assignments_tenant_period");

                    b.HasIndex("TenantId", "StudentId", "TopicId", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_topic_assignments_tenant_unique");

                    b.ToTable("student_topic_assignments", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.StudentTransferAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromGradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_grade_level_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ToGradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_grade_level_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_student_transfer_audit_entries");

                    b.HasIndex("TenantId", "PeriodId")
                        .HasDatabaseName("ix_student_transfer_audit_tenant_period");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("ix_student_transfer_audit_tenant_student");

                    b.HasIndex("TenantId", "ToGradeLevelId")
                        .HasDatabaseName("ix_student_transfer_audit_tenant_to_grade");

                    b.ToTable("student_transfer_audit_entries", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("GenderCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("gender_coded_value_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LevelOfEducationCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_of_education_coded_value_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("StaffNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("staff_number");

                    b.Property<Guid?>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TitleCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_coded_value_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("TenantId", "LastName")
                        .HasDatabaseName("ix_teachers_tenant_last_name");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherActivityAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_group_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RoleCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_coded_value_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teacher_activity_assignments");

                    b.HasIndex("ActivityGroupId")
                        .HasDatabaseName("ix_teacher_activity_assignments_activity_group_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_activity_assignments_teacher_id");

                    b.HasIndex("TenantId", "ActivityGroupId")
                        .HasDatabaseName("ix_teacher_activity_assignments_tenant_activity");

                    b.HasIndex("TenantId", "TeacherId")
                        .HasDatabaseName("ix_teacher_activity_assignments_tenant_teacher");

                    b.ToTable("teacher_activity_assignments", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherActivityAssignmentGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<Guid>("TeacherActivityAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_activity_assignment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_activity_assignment_grades");

                    b.HasIndex("TeacherActivityAssignmentId")
                        .HasDatabaseName("ix_teacher_activity_assignment_grades_teacher_activity_assignm");

                    b.HasIndex("TenantId", "GradeLevelId")
                        .HasDatabaseName("ix_teac_act_grade_tenant_grade");

                    b.HasIndex("TenantId", "TeacherActivityAssignmentId")
                        .HasDatabaseName("ix_teac_act_grade_tenant_assignment");

                    b.ToTable("teacher_activity_assignment_grades", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherGradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid?>("TeacherRoleCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_role_coded_value_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teacher_grade_levels");

                    b.HasIndex("TenantId", "GradeLevelId")
                        .HasDatabaseName("ix_teacher_grade_levels_tenant_grade_level");

                    b.HasIndex("TenantId", "TeacherId", "GradeLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_grade_levels_tenant_teacher_grade_unique_no_topic")
                        .HasFilter("\"topic_id\" IS NULL");

                    b.ToTable("teacher_grade_levels", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("coded_value_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teacher_qualifications");

                    b.HasIndex("TenantId", "TeacherId", "CodedValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_qualifications_tenant_teacher_qualification");

                    b.ToTable("teacher_qualifications", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("CodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("coded_value_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_tenant_code");

                    b.HasIndex("TenantId", "CodedValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_tenant_coded_value_id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TopicAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid?>("TopicStrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_strand_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("topic_assignment_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("topic_assignment_type");

                    b.HasKey("Id")
                        .HasName("pk_topic_assignments");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_topic_assignments_period_id");

                    b.HasIndex("TopicStrandId")
                        .HasDatabaseName("ix_topic_assignments_topic_strand_id");

                    b.HasIndex("TenantId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_topic_assignments_tenant_effective_dates");

                    b.ToTable("topic_assignments", (string)null);

                    b.HasDiscriminator<string>("topic_assignment_type").HasValue("TopicAssignment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TopicStrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentStrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_strand_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subject_strands");

                    b.HasIndex("ParentStrandId")
                        .HasDatabaseName("ix_subject_strands_parent_strand_id");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_subject_strands_topic_id");

                    b.HasIndex("TenantId", "ParentStrandId")
                        .HasDatabaseName("ix_subject_strands_tenant_parent");

                    b.HasIndex("TenantId", "TopicId")
                        .HasDatabaseName("ix_subject_strands_tenant_subject");

                    b.ToTable("subject_strands", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupTopicAssignment", b =>
                {
                    b.HasBaseType("SchoolCollab.Students.Core.Domain.TopicAssignment");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_group_id");

                    b.HasIndex("ActivityGroupId")
                        .HasDatabaseName("ix_topic_assignments_activity_group_id");

                    b.HasIndex("TenantId", "ActivityGroupId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_topic_assignments_tenant_group_topic_unique")
                        .HasFilter("\"topic_assignment_type\" = 'activity_group'");

                    b.HasDiscriminator().HasValue("activity_group");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GradeTopicAssignment", b =>
                {
                    b.HasBaseType("SchoolCollab.Students.Core.Domain.TopicAssignment");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_topic_assignments_grade_level_id");

                    b.HasIndex("TenantId", "GradeLevelId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("ix_topic_assignments_tenant_grade_topic_unique")
                        .HasFilter("\"topic_assignment_type\" = 'grade'");

                    b.HasDiscriminator().HasValue("grade");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupGradeLevel", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.ActivityGroup", null)
                        .WithMany()
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_group_grade_levels_activity_groups_activity_group_");

                    b.HasOne("SchoolCollab.Students.Core.Domain.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_group_grade_levels_grade_levels_grade_level_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupMembership", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.ActivityGroup", null)
                        .WithMany()
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_group_memberships_activity_groups_activity_group_id");

                    b.HasOne("SchoolCollab.Students.Core.Domain.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_activity_group_memberships_periods_period_id");

                    b.HasOne("SchoolCollab.Students.Core.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_group_memberships_students_student_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GradeNotificationPolicy", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_notification_policies_grade_levels_grade_level_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Period", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.Period", null)
                        .WithMany()
                        .HasForeignKey("ParentPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_periods_periods_parent_period_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherActivityAssignment", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.ActivityGroup", null)
                        .WithMany()
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_activity_assignments_activity_groups_activity_group");

                    b.HasOne("SchoolCollab.Students.Core.Domain.Teacher", null)
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_activity_assignments_teachers_teacher_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherActivityAssignmentGrade", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.TeacherActivityAssignment", null)
                        .WithMany("Grades")
                        .HasForeignKey("TeacherActivityAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_activity_assignment_grades_teacher_activity_assignm");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TopicAssignment", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_topic_assignments_periods_period_id");

                    b.HasOne("SchoolCollab.Students.Core.Domain.TopicStrand", null)
                        .WithMany()
                        .HasForeignKey("TopicStrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_topic_assignments_topic_strands_topic_strand_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TopicStrand", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.TopicStrand", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentStrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subject_strands_subject_strands_parent_strand_id");

                    b.HasOne("SchoolCollab.Students.Core.Domain.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_strands_subjects_topic_id");

                    b.Navigation("Parent");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.ActivityGroupTopicAssignment", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.ActivityGroup", null)
                        .WithMany()
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_assignments_activity_groups_activity_group_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.GradeTopicAssignment", b =>
                {
                    b.HasOne("SchoolCollab.Students.Core.Domain.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_assignments_grade_levels_grade_level_id");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.Teacher", b =>
                {
                    b.Navigation("ActivityAssignments");
                });

            modelBuilder.Entity("SchoolCollab.Students.Core.Domain.TeacherActivityAssignment", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
