// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolCollab.Settings.Core.Data;

#nullable disable

namespace SchoolCollab.Settings.Core.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260728111611_AddTenantEntityCodeRuleOverrides")]
    partial class AddTenantEntityCodeRuleOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolCollab.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Core.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.CodedValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coded_values");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_coded_values_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_coded_values_parent_id");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_coded_values_owned_tenant_parent")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("coded_values", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.EntityCodeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_entity_code_rules");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_code_rules_code_unique");

                    b.ToTable("entity_code_rules", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Boolean")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_feature_flags");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_feature_flags_key_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("feature_flags", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.FlagAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("change_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_flag_id");

                    b.Property<string>("FeatureFlagKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("feature_flag_key");

                    b.Property<bool?>("NewIsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("new_is_enabled");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool?>("PreviousIsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("previous_is_enabled");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flag_audit_entries");

                    b.HasIndex("FeatureFlagId", "OccurredAt")
                        .HasDatabaseName("ix_flag_audit_entries_flag_occurred");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_flag_audit_entries_tenant_occurred");

                    b.ToTable("flag_audit_entries", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("School")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name_unique");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.TenantCodedValueAttributeOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attribute_key");

                    b.Property<string>("CustomValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("custom_value");

                    b.Property<Guid>("GlobalCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_coded_value_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_coded_value_attribute_overrides");

                    b.HasIndex("TenantId", "GlobalCodedValueId", "AttributeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_coded_value_attribute_overrides_tenant_id_global_cod");

                    b.ToTable("tenant_coded_value_attribute_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.TenantCodedValueOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_coded_value_id");

                    b.Property<string>("OverriddenDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("overridden_description");

                    b.Property<string>("OverriddenName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("overridden_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_coded_value_overrides");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_coded_value_overrides_tenant");

                    b.HasIndex("TenantId", "GlobalCodedValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_coded_value_overrides_unique");

                    b.ToTable("tenant_coded_value_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.TenantEntityCodeRuleOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityCodeSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_code_segment_id");

                    b.Property<int>("Field")
                        .HasColumnType("integer")
                        .HasColumnName("field");

                    b.Property<Guid>("GenerationRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_rule_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tenant_entity_code_rule_overrides");

                    b.HasIndex("TenantId", "GenerationRuleId")
                        .HasDatabaseName("ix_tenant_entity_code_rule_overrides_rule");

                    b.HasIndex("TenantId", "GenerationRuleId", "EntityCodeSegmentId", "Field")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_entity_code_rule_overrides_unique");

                    b.ToTable("tenant_entity_code_rule_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.TenantFeatureFlagOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_flag_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_flag_overrides");

                    b.HasIndex("FeatureFlagId")
                        .HasDatabaseName("ix_tenant_flag_overrides_flag");

                    b.HasIndex("TenantId", "FeatureFlagId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_flag_overrides_unique")
                        .HasFilter("is_deleted = false");

                    b.ToTable("tenant_flag_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.CodedValue", b =>
                {
                    b.HasOne("SchoolCollab.Settings.Core.Domain.CodedValue", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coded_values_coded_values_parent_id");

                    b.OwnsMany("SchoolCollab.Settings.Core.Domain.CodedValueAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CodedValueId")
                                .HasColumnType("uuid")
                                .HasColumnName("coded_value_id");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.HasKey("CodedValueId", "Key")
                                .HasName("pk_coded_value_attributes");

                            b1.HasIndex("Key", "Value")
                                .HasDatabaseName("ix_coded_value_attributes_key_value");

                            b1.ToTable("coded_value_attributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodedValueId")
                                .HasConstraintName("fk_coded_value_attributes_coded_values_coded_value_id");
                        });

                    b.OwnsMany("SchoolCollab.Settings.Core.Domain.CodedValueAttributeDefinition", "AttributeDefinitions", b1 =>
                        {
                            b1.Property<Guid>("CodedValueId")
                                .HasColumnType("uuid")
                                .HasColumnName("coded_value_id");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<bool>("AllowMultiple")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("allow_multiple");

                            b1.Property<int>("DataType")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("data_type");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<bool>("IsRequired")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_required");

                            b1.Property<int?>("MaxLength")
                                .HasColumnType("integer")
                                .HasColumnName("max_length");

                            b1.Property<int?>("MinLength")
                                .HasColumnType("integer")
                                .HasColumnName("min_length");

                            b1.Property<string>("RegexPattern")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("regex_pattern");

                            b1.Property<string>("SourceCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_code");

                            b1.HasKey("CodedValueId", "Key")
                                .HasName("pk_coded_value_attribute_definitions");

                            b1.HasIndex("Key")
                                .HasDatabaseName("ix_coded_value_attribute_definitions_key");

                            b1.ToTable("coded_value_attribute_definitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodedValueId")
                                .HasConstraintName("fk_coded_value_attribute_definitions_coded_values_coded_value_");
                        });

                    b.Navigation("AttributeDefinitions");

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.EntityCodeRule", b =>
                {
                    b.OwnsMany("SchoolCollab.Settings.Core.Domain.EntityCodeSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EntityCodeRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_code_rule_id");

                            b1.Property<string>("FixedText")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("fixed_text");

                            b1.Property<int>("Index")
                                .HasColumnType("integer")
                                .HasColumnName("index");

                            b1.Property<string>("LastPeriodBucket")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("last_period_bucket");

                            b1.Property<string>("LastPrefix")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("last_prefix");

                            b1.Property<int>("LastSequence")
                                .HasColumnType("integer")
                                .HasColumnName("last_sequence");

                            b1.Property<int>("MinWidth")
                                .HasColumnType("integer")
                                .HasColumnName("min_width");

                            b1.Property<string>("Prefix")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("prefix");

                            b1.Property<int>("ResetPeriod")
                                .HasColumnType("integer")
                                .HasColumnName("reset_period");

                            b1.Property<string>("Role")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("role");

                            b1.Property<string>("Suffix")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("suffix");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<string>("UpperLimit")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("upper_limit");

                            b1.HasKey("Id")
                                .HasName("pk_entity_code_segments");

                            b1.HasIndex("EntityCodeRuleId", "Index")
                                .IsUnique()
                                .HasDatabaseName("ix_entity_code_segments_rule_index_unique");

                            b1.ToTable("entity_code_segments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntityCodeRuleId")
                                .HasConstraintName("fk_entity_code_segments_entity_code_rules_entity_code_rule_id");
                        });

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("SchoolCollab.Settings.Core.Domain.TenantFeatureFlagOverride", b =>
                {
                    b.HasOne("SchoolCollab.Settings.Core.Domain.FeatureFlag", null)
                        .WithMany()
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_flag_overrides_feature_flags_feature_flag_id");
                });
#pragma warning restore 612, 618
        }
    }
}
