// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolCollab.Assignments.Core.Data;

#nullable disable

namespace SchoolCollab.Assignments.Core.Migrations
{
    [DbContext(typeof(AssignmentsDbContext))]
    [Migration("20260616101810_AddGradingFormatAndTargetAudience")]
    partial class AddGradingFormatAndTargetAudience
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssignmentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assignment_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_teacher_id");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("GradeCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_coded_value_id");

                    b.Property<int>("GradingFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("grading_format");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_coded_value_id");

                    b.Property<int>("TargetAudience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("target_audience");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("CreatedByTeacherId")
                        .HasDatabaseName("ix_assignments_teacher_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.HasIndex("SubjectCodedValueId")
                        .HasDatabaseName("ix_assignments_subject_cv_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.Assignment", b =>
                {
                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size");

                            b1.Property<string>("StoragePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("storage_path");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_attachments");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_attachments_assignment_id");

                            b1.ToTable("assignment_attachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_attachments_assignments_assignment_id");
                        });

                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<Guid?>("CorrectOptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("correct_option_id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<string>("QuestionText")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("question_text");

                            b1.Property<int>("QuestionType")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("question_type");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_questions");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_questions_assignment_id");

                            b1.ToTable("assignment_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_questions_assignments_assignment_id");

                            b1.OwnsMany("SchoolCollab.Assignments.Core.Domain.QuestionOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<bool>("IsCorrect")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("is_correct");

                                    b2.Property<string>("OptionText")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("option_text");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("question_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_question_options");

                                    b2.HasIndex("QuestionId")
                                        .HasDatabaseName("ix_question_options_question_id");

                                    b2.ToTable("question_options", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionId")
                                        .HasConstraintName("fk_question_options_assignment_questions_question_id");
                                });

                            b1.Navigation("Options");
                        });

                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<string>("Comments")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("comments");

                            b1.Property<DateTimeOffset>("ReviewDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("review_date");

                            b1.Property<decimal?>("Score")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("score");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_reviews");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_reviews_assignment_id");

                            b1.ToTable("assignment_reviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_reviews_assignments_assignment_id");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Questions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
