// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolCollab.Assignments.Core.Data;

#nullable disable

namespace SchoolCollab.Assignments.Core.Migrations
{
    [DbContext(typeof(AssignmentsDbContext))]
    partial class AssignmentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_number");

                    b.Property<int>("AssignmentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assignment_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_teacher_id");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<int>("GradingFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("grading_format");

                    b.Property<bool>("MandatoryReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("mandatory_review");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int>("TargetAudienceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("target_audience_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("CreatedByTeacherId")
                        .HasDatabaseName("ix_assignments_teacher_id");

                    b.HasIndex("GradeLevelId")
                        .HasDatabaseName("ix_assignments_grade_level_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_assignments_topic_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.AssignmentActivityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_group_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_activity_groups");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_activity_groups_assignment_id");

                    b.HasIndex("TenantId", "ActivityGroupId")
                        .HasDatabaseName("ix_assignment_activity_groups_tenant_group");

                    b.HasIndex("TenantId", "AssignmentId", "ActivityGroupId")
                        .IsUnique()
                        .HasDatabaseName("uq_assignment_activity_groups_tenant_assignment_group");

                    b.ToTable("assignment_activity_groups", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.AssignmentRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<bool>("NotifyOnBroadcast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_on_broadcast");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<int?>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<bool>("SubscriptionActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("subscription_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WardStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ward_student_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_recipients");

                    b.HasIndex("AssignmentId", "OwnerId")
                        .HasDatabaseName("ix_assignment_recipients_assignment_owner");

                    b.HasIndex("TenantId", "AssignmentId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("uq_assignment_recipients_tenant_assignment_contact");

                    b.ToTable("assignment_recipients", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.AssignmentSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_source");

                    b.Property<int>("CurrentVersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_version_number");

                    b.Property<DateTimeOffset>("LastSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_at");

                    b.Property<int>("ReviewState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_state");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("SubmissionGateId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_gate_id");

                    b.Property<Guid?>("SubmittedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_guardian_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_submissions");

                    b.HasIndex("TenantId", "AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("uq_assignment_submissions_tenant_assignment_student");

                    b.ToTable("assignment_submissions", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.AssignmentSubmissionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Content")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_guardian_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_assignment_submission_versions");

                    b.HasIndex("TenantId", "SubmissionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_assignment_submission_versions_tenant_submission_version");

                    b.ToTable("assignment_submission_versions", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.GuardianSubmissionGate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_comment");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_guardian_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<bool>("SubmissionEnabledForStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("submission_enabled_for_student");

                    b.Property<DateTimeOffset?>("SubmittedByGuardianAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_by_guardian_at");

                    b.Property<Guid?>("SubmittedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_guardian_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guardian_submission_gates");

                    b.HasIndex("TenantId", "AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("uq_guardian_submission_gates_tenant_assignment_student");

                    b.ToTable("guardian_submission_gates", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.SubmissionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comments");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submission_reviews");

                    b.HasIndex("TenantId", "SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_submission_reviews_tenant_submission");

                    b.ToTable("submission_reviews", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Core.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.Assignment", b =>
                {
                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size");

                            b1.Property<string>("StoragePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("storage_path");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_attachments");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_attachments_assignment_id");

                            b1.ToTable("assignment_attachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_attachments_assignments_assignment_id");
                        });

                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<Guid?>("CorrectOptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("correct_option_id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<string>("QuestionText")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("question_text");

                            b1.Property<int>("QuestionType")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("question_type");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_questions");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_questions_assignment_id");

                            b1.ToTable("assignment_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_questions_assignments_assignment_id");

                            b1.OwnsMany("SchoolCollab.Assignments.Core.Domain.QuestionOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<bool>("IsCorrect")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("is_correct");

                                    b2.Property<string>("OptionText")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("option_text");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("question_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_question_options");

                                    b2.HasIndex("QuestionId")
                                        .HasDatabaseName("ix_question_options_question_id");

                                    b2.ToTable("question_options", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionId")
                                        .HasConstraintName("fk_question_options_assignment_questions_question_id");
                                });

                            b1.Navigation("Options");
                        });

                    b.OwnsMany("SchoolCollab.Assignments.Core.Domain.AssignmentReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<string>("Comments")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("comments");

                            b1.Property<DateTimeOffset>("ReviewDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("review_date");

                            b1.Property<decimal?>("Score")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("score");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.HasKey("Id")
                                .HasName("pk_assignment_reviews");

                            b1.HasIndex("AssignmentId")
                                .HasDatabaseName("ix_assignment_reviews_assignment_id");

                            b1.ToTable("assignment_reviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId")
                                .HasConstraintName("fk_assignment_reviews_assignments_assignment_id");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Questions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SchoolCollab.Assignments.Core.Domain.AssignmentActivityGroup", b =>
                {
                    b.HasOne("SchoolCollab.Assignments.Core.Domain.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_activity_groups_assignments_assignment_id");
                });
#pragma warning restore 612, 618
        }
    }
}
