// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolCollab.CodedValues.Core.Data;

#nullable disable

namespace SchoolCollab.CodedValues.Core.Data.Migrations
{
    [DbContext(typeof(CodedValuesDbContext))]
    [Migration("20260629102643_UseSharedOutboxMessage")]
    partial class UseSharedOutboxMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolCollab.CodedValues.Core.Domain.CodedValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coded_values");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_coded_values_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_coded_values_parent_id");

                    b.ToTable("coded_values", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.CodedValues.Core.Domain.TenantCodedValueAttributeOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attribute_key");

                    b.Property<string>("CustomValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("custom_value");

                    b.Property<Guid>("GlobalCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_coded_value_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_coded_value_attribute_overrides");

                    b.HasIndex("TenantId", "GlobalCodedValueId", "AttributeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_coded_value_attribute_overrides_tenant_id_global_cod");

                    b.ToTable("tenant_coded_value_attribute_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.CodedValues.Core.Domain.TenantCodedValueOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalCodedValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_coded_value_id");

                    b.Property<string>("OverriddenDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("overridden_description");

                    b.Property<string>("OverriddenName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("overridden_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_coded_value_overrides");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_coded_value_overrides_tenant");

                    b.HasIndex("TenantId", "GlobalCodedValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_coded_value_overrides_unique");

                    b.ToTable("tenant_coded_value_overrides", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.Core.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SchoolCollab.CodedValues.Core.Domain.CodedValue", b =>
                {
                    b.HasOne("SchoolCollab.CodedValues.Core.Domain.CodedValue", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coded_values_coded_values_parent_id");

                    b.OwnsMany("SchoolCollab.CodedValues.Core.Domain.CodedValueAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CodedValueId")
                                .HasColumnType("uuid")
                                .HasColumnName("coded_value_id");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.HasKey("CodedValueId", "Key")
                                .HasName("pk_coded_value_attributes");

                            b1.HasIndex("Key", "Value")
                                .HasDatabaseName("ix_coded_value_attributes_key_value");

                            b1.ToTable("coded_value_attributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodedValueId")
                                .HasConstraintName("fk_coded_value_attributes_coded_values_coded_value_id");
                        });

                    b.OwnsMany("SchoolCollab.CodedValues.Core.Domain.CodedValueAttributeDefinition", "AttributeDefinitions", b1 =>
                        {
                            b1.Property<Guid>("CodedValueId")
                                .HasColumnType("uuid")
                                .HasColumnName("coded_value_id");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<bool>("AllowMultiple")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("allow_multiple");

                            b1.Property<int>("DataType")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("data_type");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<bool>("IsRequired")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_required");

                            b1.Property<int?>("MaxLength")
                                .HasColumnType("integer")
                                .HasColumnName("max_length");

                            b1.Property<int?>("MinLength")
                                .HasColumnType("integer")
                                .HasColumnName("min_length");

                            b1.Property<string>("RegexPattern")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("regex_pattern");

                            b1.Property<string>("SourceCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_code");

                            b1.HasKey("CodedValueId", "Key")
                                .HasName("pk_coded_value_attribute_definitions");

                            b1.HasIndex("Key")
                                .HasDatabaseName("ix_coded_value_attribute_definitions_key");

                            b1.ToTable("coded_value_attribute_definitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodedValueId")
                                .HasConstraintName("fk_coded_value_attribute_definitions_coded_values_coded_value_");
                        });

                    b.Navigation("AttributeDefinitions");

                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
