<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Config\SchoolCollab.Config.Core\SchoolCollab.Config.Core.csproj" />
    <ProjectReference Include="..\..\src\Config\SchoolCollab.Config.Api\SchoolCollab.Config.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>
</Project>