<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\SchoolCollab.ServiceDefaults\SchoolCollab.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Settings\SchoolCollab.Settings.Core\SchoolCollab.Settings.Core.csproj" />
    <ProjectReference Include="..\Assignments\SchoolCollab.Assignments.Core\SchoolCollab.Assignments.Core.csproj" />
    <ProjectReference Include="..\Students\SchoolCollab.Students.Core\SchoolCollab.Students.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="SeedData\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
