<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0436</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SchoolCollab.Admin.Shared\SchoolCollab.Admin.Shared.csproj" />
    <ProjectReference Include="..\Settings\SchoolCollab.Settings.Application\SchoolCollab.Settings.Application.csproj" />
    <ProjectReference Include="..\Assignments\SchoolCollab.Assignments.Application\SchoolCollab.Assignments.Application.csproj" />
    <ProjectReference Include="..\Students\SchoolCollab.Students.Application\SchoolCollab.Students.Application.csproj" />
    <ProjectReference Include="..\ServiceDefaults\SchoolCollab.ServiceDefaults\SchoolCollab.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AI\SchoolCollab.AI.Server\SchoolCollab.AI.Server.csproj" />
    <ProjectReference Include="..\SchoolCollab.Core\SchoolCollab.Core.csproj" />
  </ItemGroup>
</Project>
