<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0436</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SchoolCollab.Admin.Shared\SchoolCollab.Admin.Shared.csproj" />
    <ProjectReference Include="..\CodedValues\SchoolCollab.CodedValues.Admin\SchoolCollab.CodedValues.Admin.csproj" />
    <ProjectReference Include="..\Assignments\SchoolCollab.Assignments.Admin\SchoolCollab.Assignments.Admin.csproj" />
    <ProjectReference Include="..\Students\SchoolCollab.Students.Admin\SchoolCollab.Students.Admin.csproj" />
    <ProjectReference Include="..\ServiceDefaults\SchoolCollab.ServiceDefaults\SchoolCollab.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SchoolCollab.AI\SchoolCollab.AI.csproj" />
  </ItemGroup>
</Project>